import { useState, useMemo } from 'react';
import { useMedication } from '../context/MedicationContext';
import { useAuth } from '../context/AuthContext';
import { format, subDays } from 'date-fns';
import { DocumentArrowDownIcon, PrinterIcon, CheckCircleIcon } from '@heroicons/react/24/outline';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Cell,
} from 'recharts';
import toast from 'react-hot-toast';

function BarTooltip({ active, payload, label }) {
  if (!active || !payload?.length) return null;
  return (
    <div style={{ background: 'var(--neutral-800)', border: '1px solid var(--glass-border)', borderRadius: 8, padding: '8px 12px', fontSize: '0.8rem' }}>
      <div className="text-muted mb-1">{label}</div>
      <div className="text-white font-semibold">{payload[0]?.value} doses</div>
    </div>
  );
}

export default function ReportsPage() {
  const { user } = useAuth();
  const { medications, allLogs, prnLogs, userProfile, interactions } = useMedication();
  const [days, setDays] = useState(7);
  const [printing, setPrinting] = useState(false);

  const activeMeds = medications.filter(m => m.status === 'active');

  // Per-medication adherence
  const medAdherence = useMemo(() => {
    return activeMeds.map(med => {
      const scheduled = (med.schedule?.length || 0) * days;
      const taken = allLogs.filter(l => {
        if (l.medicationId !== med.id) return false;
        const d = l.date;
        if (!d) return false;
        const diff = (new Date() - new Date(d + 'T00:00:00')) / 86400000;
        return diff <= days;
      }).length;
      return {
        name: med.brandName,
        scheduled,
        taken,
        rate: scheduled > 0 ? Math.round((taken / scheduled) * 100) : 0,
        color: med.color || '#6366f1',
      };
    });
  }, [activeMeds, allLogs, days]);

  // Daily bar chart
  const barData = useMemo(() => {
    return Array.from({ length: days }, (_, i) => {
      const date = subDays(new Date(), days - 1 - i);
      const dateStr = format(date, 'yyyy-MM-dd');
      const count = allLogs.filter(l => l.date === dateStr).length;
      return { day: format(date, days <= 7 ? 'EEE' : 'MMM d'), doses: count };
    });
  }, [allLogs, days]);

  const overallAdherence = useMemo(() => {
    const total = medAdherence.reduce((acc, m) => acc + m.scheduled, 0);
    const taken = medAdherence.reduce((acc, m) => acc + m.taken, 0);
    return total > 0 ? Math.round((taken / total) * 100) : 0;
  }, [medAdherence]);

  const handlePrint = () => {
    setPrinting(true);
    setTimeout(() => {
      window.print();
      setPrinting(false);
    }, 300);
  };

  const handleExportText = () => {
    const lines = [
      '===================================================',
      '           MEDTRACK AI — DOCTOR REPORT             ',
      '===================================================',
      '',
      `Patient Name  : ${userProfile?.displayName || user?.displayName || 'N/A'}`,
      `Email         : ${user?.email || 'N/A'}`,
      `Doctor        : ${userProfile?.doctorName || 'N/A'}`,
      `Report Date   : ${format(new Date(), 'MMMM d, yyyy')}`,
      `Report Period : Last ${days} days`,
      '',
      '--- ACTIVE MEDICATIONS ---',
      ...activeMeds.map(m =>
        `• ${m.brandName} (${m.genericName || 'N/A'}) — ${m.dosage} — ${m.frequency?.replace('_', ' ')} — Pills left: ${m.pillCount ?? 'N/A'}`
      ),
      '',
      '--- ADHERENCE SUMMARY ---',
      `Overall Adherence: ${overallAdherence}%`,
      ...medAdherence.map(m => `• ${m.name}: ${m.taken}/${m.scheduled} doses (${m.rate}%)`),
      '',
      '--- DRUG INTERACTIONS ---',
      interactions.length === 0 ? 'No interactions detected.' :
        interactions.map(i => `• [${i.severity.toUpperCase()}] ${i.drug1} ↔ ${i.drug2}: ${i.description}`).join('\n'),
      '',
      '--- PRN MEDICATIONS (last ' + days + ' days) ---',
      prnLogs.length === 0 ? 'No PRN logs.' :
        prnLogs.slice(0, 20).map(l => `• ${l.date} ${l.time || ''} — ${l.medicationName} ${l.dosage || ''} — ${l.reason || ''}`).join('\n'),
      '',
      `Generated by MedTrack AI on ${format(new Date(), 'PPpp')}`,
      '===================================================',
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MedTrack_Report_${format(new Date(), 'yyyy-MM-dd')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded!');
  };

  return (
    <div style={{ padding: '28px 24px', maxWidth: 1000, margin: '0 auto' }} id="report-content">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3 mb-6 animate-fade-in">
        <div>
          <h1 className="text-display font-extrabold text-white text-2xl">Doctor Report</h1>
          <p className="text-sm text-muted mt-0.5">Shareable medication & adherence summary</p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <button className="btn btn-secondary" onClick={handlePrint} disabled={printing}>
            <PrinterIcon style={{ width: 16, height: 16 }} />
            Print
          </button>
          <button id="export-report-btn" className="btn btn-primary" onClick={handleExportText}>
            <DocumentArrowDownIcon style={{ width: 16, height: 16 }} />
            Export .txt
          </button>
        </div>
      </div>

      {/* Period Selector */}
      <div className="flex gap-2 mb-6 animate-fade-in">
        {[7, 14, 30].map(d => (
          <button
            key={d}
            className={`btn btn-sm ${days === d ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => setDays(d)}
          >
            {d} days
          </button>
        ))}
      </div>

      {/* Patient Info Card */}
      <div className="glass-card animate-fade-in mb-6" style={{ padding: 24 }}>
        <div style={{
          display: 'flex', gap: 24, flexWrap: 'wrap',
          paddingBottom: 20, borderBottom: '1px solid var(--glass-border)', marginBottom: 20,
        }}>
          <div>
            <div className="text-xs text-muted uppercase tracking-widest font-semibold mb-1">Patient</div>
            <div className="font-bold text-white text-base">{userProfile?.displayName || user?.displayName || 'N/A'}</div>
            <div className="text-sm text-muted">{user?.email}</div>
          </div>
          {userProfile?.age && (
            <div>
              <div className="text-xs text-muted uppercase tracking-widest font-semibold mb-1">Age</div>
              <div className="font-semibold text-white">{userProfile.age} years</div>
            </div>
          )}
          {userProfile?.bloodType && (
            <div>
              <div className="text-xs text-muted uppercase tracking-widest font-semibold mb-1">Blood Type</div>
              <div className="font-semibold text-white">{userProfile.bloodType}</div>
            </div>
          )}
          {userProfile?.doctorName && (
            <div>
              <div className="text-xs text-muted uppercase tracking-widest font-semibold mb-1">Doctor</div>
              <div className="font-semibold text-white">{userProfile.doctorName}</div>
            </div>
          )}
          <div className="ml-auto">
            <div className="text-xs text-muted uppercase tracking-widest font-semibold mb-1">Report Date</div>
            <div className="font-semibold text-white">{format(new Date(), 'MMM d, yyyy')}</div>
            <div className="text-xs text-muted">Last {days} days</div>
          </div>
        </div>

        {/* Quick stats */}
        <div className="grid grid-4 gap-4">
          {[
            { label: 'Active Medications', value: activeMeds.length, color: 'var(--primary-400)' },
            { label: 'Overall Adherence', value: `${overallAdherence}%`, color: overallAdherence >= 80 ? 'var(--accent-400)' : 'var(--warning-400)' },
            { label: 'Interactions', value: interactions.length, color: interactions.length > 0 ? 'var(--danger-400)' : 'var(--accent-400)' },
            { label: 'PRN Uses', value: prnLogs.filter(l => {
              const diff = (new Date() - new Date(l.date + 'T00:00:00')) / 86400000;
              return diff <= days;
            }).length, color: 'var(--neutral-300)' },
          ].map(stat => (
            <div key={stat.label} style={{ textAlign: 'center' }}>
              <div style={{ fontSize: '1.5rem', fontWeight: 800, color: stat.color, fontFamily: 'Plus Jakarta Sans' }}>
                {stat.value}
              </div>
              <div className="text-xs text-muted">{stat.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Charts + Adherence */}
      <div className="grid gap-6 mb-6" style={{ gridTemplateColumns: '1fr 1fr' }}>
        {/* Bar Chart */}
        <div className="glass-card" style={{ padding: 24 }}>
          <div className="font-bold text-white text-sm mb-4">Daily Dose Log</div>
          <ResponsiveContainer width="100%" height={180}>
            <BarChart data={barData} margin={{ top: 4, right: 4, left: -20, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" />
              <XAxis dataKey="day" tick={{ fill: '#6b6b9a', fontSize: 11 }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fill: '#6b6b9a', fontSize: 11 }} axisLine={false} tickLine={false} />
              <Tooltip content={<BarTooltip />} />
              <Bar dataKey="doses" radius={[4, 4, 0, 0]}>
                {barData.map((entry, i) => (
                  <Cell key={i} fill={entry.doses > 0 ? '#6366f1' : '#252540'} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>

        {/* Per-Med Adherence */}
        <div className="glass-card" style={{ padding: 24 }}>
          <div className="font-bold text-white text-sm mb-4">Per-Medication Adherence</div>
          {medAdherence.length === 0 ? (
            <div className="text-sm text-muted">No active medications to report.</div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {medAdherence.map(m => (
                <div key={m.name}>
                  <div className="flex justify-between mb-1">
                    <span className="text-sm font-semibold text-white">{m.name}</span>
                    <span className="text-sm font-bold" style={{ color: m.rate >= 80 ? 'var(--accent-400)' : 'var(--warning-400)' }}>
                      {m.rate}%
                    </span>
                  </div>
                  <div className="progress-bar-track">
                    <div
                      className="progress-bar-fill"
                      style={{
                        width: `${m.rate}%`,
                        background: m.rate >= 80
                          ? 'linear-gradient(90deg, var(--accent-500), var(--accent-400))'
                          : 'linear-gradient(90deg, var(--warning-400), var(--danger-400))',
                      }}
                    />
                  </div>
                  <div className="text-xs text-muted mt-0.5">{m.taken}/{m.scheduled} doses</div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Medication List */}
      <div className="glass-card animate-fade-in mb-6" style={{ padding: 24 }}>
        <div className="font-bold text-white text-base mb-4">Current Medications</div>
        {activeMeds.length === 0 ? (
          <div className="text-sm text-muted">No active medications.</div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Medication</th>
                <th>Dosage</th>
                <th>Frequency</th>
                <th>Schedule</th>
                <th>Pills Left</th>
              </tr>
            </thead>
            <tbody>
              {activeMeds.map(med => (
                <tr key={med.id}>
                  <td>
                    <div className="flex items-center gap-2">
                      <div style={{ width: 8, height: 8, borderRadius: '50%', background: med.color || '#6366f1', flexShrink: 0 }} />
                      <div>
                        <div className="font-semibold text-white">{med.brandName}</div>
                        {med.genericName && <div className="text-xs text-muted">{med.genericName}</div>}
                      </div>
                    </div>
                  </td>
                  <td className="text-sm" style={{ color: 'var(--neutral-300)' }}>{med.dosage}</td>
                  <td className="text-sm" style={{ color: 'var(--neutral-300)' }}>{med.frequency?.replace('_', ' ')}</td>
                  <td className="text-sm" style={{ color: 'var(--neutral-300)' }}>{med.schedule?.join(', ') || '—'}</td>
                  <td>
                    {med.pillCount !== undefined ? (
                      <span className={`badge ${med.pillCount <= 7 ? 'badge-warning' : 'badge-success'}`}>
                        {med.pillCount}
                      </span>
                    ) : '—'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Interactions Summary */}
      {interactions.length > 0 && (
        <div className="glass-card animate-fade-in mb-6" style={{ padding: 24 }}>
          <div className="font-bold text-white text-base mb-4">⚠️ Drug Interactions</div>
          <table className="data-table">
            <thead>
              <tr>
                <th>Drug 1</th>
                <th>Drug 2</th>
                <th>Severity</th>
                <th>Note</th>
              </tr>
            </thead>
            <tbody>
              {interactions.map(i => (
                <tr key={i.id}>
                  <td className="font-semibold text-white">{i.drug1}</td>
                  <td className="font-semibold text-white">{i.drug2}</td>
                  <td>
                    <span className={`badge badge-${i.severity === 'severe' ? 'danger' : i.severity === 'moderate' ? 'warning' : 'primary'}`}>
                      {i.severity}
                    </span>
                  </td>
                  <td className="text-xs" style={{ color: 'var(--neutral-400)', maxWidth: 240 }}>
                    {i.description.substring(0, 100)}...
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* PRN Summary */}
      <div className="glass-card animate-fade-in" style={{ padding: 24 }}>
        <div className="font-bold text-white text-base mb-4">
          PRN Medication Uses (last {days} days)
        </div>
        {prnLogs.length === 0 ? (
          <div className="text-sm text-muted">No PRN logs in this period.</div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Medication</th>
                <th>Dosage</th>
                <th>Reason</th>
                <th>Effectiveness</th>
              </tr>
            </thead>
            <tbody>
              {prnLogs.slice(0, 20).map(log => (
                <tr key={log.id}>
                  <td className="text-sm" style={{ color: 'var(--neutral-300)' }}>{log.date}</td>
                  <td className="text-sm" style={{ color: 'var(--neutral-300)' }}>{log.time || '—'}</td>
                  <td className="font-semibold text-white">{log.medicationName}</td>
                  <td className="text-sm" style={{ color: 'var(--neutral-300)' }}>{log.dosage || '—'}</td>
                  <td className="text-sm" style={{ color: 'var(--neutral-300)' }}>{log.reason || '—'}</td>
                  <td>
                    {log.effectiveness ? (
                      <span className="text-sm font-semibold" style={{ color: 'var(--accent-400)' }}>
                        {'★'.repeat(log.effectiveness)}{'☆'.repeat(5 - log.effectiveness)}
                      </span>
                    ) : '—'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      <style>{`
        @media print {
          .sidebar, header { display: none !important; }
          .main-content { margin-left: 0 !important; }
          body { background: white !important; color: black !important; }
        }
        @media (max-width: 700px) {
          .grid[style*="1fr 1fr"] { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </div>
  );
}
